[tool.poetry]
name = "game-project"
version = "0.1.0"
description = ""
authors = ["Rodrigo Cristiano <rcristianofv@hotmail.com>"]
packages = [{include = "engine"}]

[tool.poetry.dependencies]
python = "^3.10"
pygame = "^2.4.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
